export const CoreProfessionalCompetenciesConstant = [
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.CONFLICT_RESOLUTION', value: 7 },
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.TEAM_ORIENTATION', value: 8 },
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.LEADERSHIP', value: 7 },
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.MENTORSHIP', value: 9 },
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.NETWORKING', value: 6 },
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.HUMILITY', value: 7 },
  { key: 'CHARTS.CORE_PROFESSIONAL_COMPETENCIES.DECISION_MAKING', value: 8 },
] as const;

export const CorePersonalQualitiesConstant = [
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.MOTIVATION', value: 8 },
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.TRUSTWORTHINESS', value: 9 },
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.RESPECTFULNESS', value: 9 },
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.CONFIDENCE', value: 8 },
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.OPENNESS', value: 7 },
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.ADAPTABILITY', value: 10 },
  { key: 'CHARTS.CORE_PERSONAL_QUALITIES.SELF_AWARENESS', value: 9 },
] as const;
